function bmp = bmpmake_w(depv, indv, pthstack, vg, opt, opt2)

%depv (roi,time), or empty if using opt to define depv via vget 
%indv (roi,time), or empty if using opt to define indv via vget 

% options for bump in bmpmake function
% a von mises is fit to the instantaneous relationship between each roi timeseries (given by all matches from o.bmp.mdl.vg.v1) and all matches from o.bmp.mdl.vg.v2
% the value of the independent variable at the max predicted response is the preferred heading for each roi
% if o.bmp.domaintypeis 'functional', these preferred headings are used as the angle, and o.bmp.mdl.vg.v1 as the magnitude, in computing pva
% if the rgname in o.bmp.mdl.vg.v1 is in o.bmp.numangrs, and that rgname is followed by hyphen and number greater than zero, these preferred heading angles are resampled into that number, so that the rois evenly sample range 0-2pi (resampling changes angle and magnitude)
% if o.bmp.domaintypeis 'morphological', angle is forced to be 0-2pi, with each roi evenly sampling that range

arguments

    depv = []
    indv = []
    pthstack = []

    vg.indv = []
    vg.depv = []

    opt.domtype = 'm' %'f' (functional) to define circular domain with fit to each roi, or 'm' (morphological) to define as circle across region mask
    opt.numcirc = 1 %number of circles (eg 1 for eb, 2 for pb), if pb, always use 2 because you can subset with argument 'scope' below
    opt.mthd = 'pva' %'pva' for vector average, pvas for signed vector average, vm for fit von mises to activity across all roi at each sample
    opt.scope = 'all' %which part of compass to use in computing bump parameters, using anything but 'all' doesn't make much sense uunless you have a 2-circle structure, like pb; cell array of char, 'all', 'right', 'left', 'max', 'random', or a digits (numeric or text) denoting left half percentage weight (right will be 100-left)
    opt.dvord = 2 %order of polynomial used to fit sliding window slope (to compute bump speed)
    opt.dvlensec = 0.4 %length of window (in seconds) used to fit sliding window slope (to compute bump speed); rounded to nearest sample
    opt.smlensec = 0 %full width of gaussian smoothing window (5 times std)
    opt.numangrs = 16 %how many clusters/superrois across the entire region (not hemisphere) when resampled uniformly prior to computing bump as vector average
    opt.maxangrs = 8 %max number resolvable ("unaliased") angles in resampled output (ie 1/maxangrs) is highest frequency you wish to capture in output)opt.smfac = 1; %when resampling compass, bandwidth of the antialiasing filter, larger number will have smoother resampled compass
    opt.dorescale = 0 %just before computing bump, rescale each cluster's timeseries to range 0-1
    opt.omitnan = 1 %ignore nans in case there are any (e.g., making hybrid morph-func rois, some morph rois have no func members, making their response 'nan', omit will ignore this in computing pva)
    opt.mdl = [] %mdlmake options returned by mdlmake(och=1); empty to skip mdlmake from within bmpmake; fits models to input timeseries to find each roi's preferred head direction
    opt.optid = '' %automatically generated id for each unique input opt set; if your input opt is not generated by oset, leave optid empty
    opt.varid = ''%automatically generated id for each unique input variable set; if your input variables are not generated by vget, leave varid empty

    opt2.srate = []
    opt2.epochts = []
    opt2.doplt = 0 % 1 to make plots
    opt2.och (1,1) {mustBeBinary} = 0 %och means "options check"; 1 to exit function and return nothing but arguments block struct opt (not opt2 or any other name-value arguments struct); 0 to skip och (run function normally), which is default

end

if opt2.och
    prs = struct2pairs(opt);
    bmp = bmpmake('', prs{:}, och=1); %use arguments block in module to validate all name-value arguments in 'opt'
    bmp = rmfield(bmp, {'optid', 'varid'});
    if opt2.och==2
        if ~isempty(opt.optid) %use opt.optid instead of bmp.optid because optid and varid were removed from bmp
            error("optid must be empty if och==2, since och=2 is a flag for deriving optid")
        end
        bmp = oid(bmp, mos='bmp'); %assign ids to options sets
    end
    return
end

%% set up indv/depv

if strcmp(opt.domtype, 'f') && ~isequal(isempty(indv), isempty(depv), ~isempty(opt.indv.vg), ~isempty(opt.depv.vg))
    error("if domtype is 'f', indv and depv must both be empty or nonempty, with opt.indv and opt.depv the inverse")
end
if strcmp(opt.domtype, 'm')
    % indv = []; 
    % opt.indv = []; 
    if ~isequal(isempty(depv), ~isempty(opt.depv.vg))
        error("if domtype is 'm', depv must be empty or nonempty, with opt.depv the inverse; indv and opt.indv will be set to empty and ignored")
    end
end

if isempty(indv) && isempty(depv)
    dovget = 1;
end

clear vget %clear persistent variables within vget (just in case)
its = 0;
while true
    its = its+1;

    if dovget %if indv/depv are defined in the options struct, instead of passed in as arguments
        [vdat, indv, depv] = vget(its, opt.indv, opt.depv);
        varid = vdat.varid;
        last = vdat.last;
        pthbmp = [vdat.pthc vdat.varid opt.optid '_bmp_.mat'];
    else
        varid = 'z0';
        last = 1;
        pthbmp = [erase(pthstack, {'_.mat', '.mat'}) '_' varid opt.optid '_bmp_.mat'];
    end

    bmp(its) = bmpmake(depv, indv, pthbmp, opt, opt2);

    if last
        break
    end
end

end