function [fmf, opt] = fmfmake(s, opt, opt2)

%just mat files right now, will include binaries soon and be renamed load_flymax_movie

arguments

    s = '' % if struct, s is the struct output from function smake (contains stack, md, pth, and other fields); if struct, pthsv (output bmp file path) is derived from s.pth (path to stack); if char, s is path to stack depv and indv are associated with; if empty, error
    
    opt.stimtype {mustBeTextScalar} = 'drone';
    opt.id {mustBeTextScalar} = '';
    opt.crop_edges (1,1) {mustBeBinary} = 1;
    opt.rep (1,1) {mustBeInteger, mustBePositive} = 1;
    opt.flipped (1,1) {mustBeBinary} = 0;
    opt.feat2 {mustBeTextScalar} = '';
    
    opt2.pthpar {mustBeTextScalar} = '';
    opt2.pthtemplate {mustBeTextScalar} = '';
    opt2.getgrid (1,1) {mustBeBinary} = 1; %get the feature on a grid (phi theta if vistype is sphere, xy if gridtype is plane)
    opt2.vistype {mustBeTextScalar} = 'plane'; %sphere, plane, or raw
    opt2.it {mustBeNumeric} = -100;
    opt2.gridres (1,1) {mustBeInteger, mustBePositive} = 256;
    opt2.downsample_template (1,1) {mustBeBinary} = 1; %downsamples template, then uses it, rather than using template then downsampling; fine for most cases, just looks a little rougher
    opt2.doplt (1,1) {mustBeBinary} = 0 % 1 to make plots
    opt2.optid {mustBeTextScalar} = glbfile('optiddf'); %automatically generated id for unique set of input options; if your input opt is not generated by oset, leave optid empty
    opt2.varid {mustBeTextScalar} = glbfile('variddf'); %automatically generated id for unique set of input variables; if your input variables are not generated by vget, leave varid empty
    opt2.runtype (1,1) {mustBeBinary} = 0 %runtype controls how much of this function to run; 0 to run entire function; 1 to do nothing but validate input arguments and return arguments block struct opt (not any other input arguments, since only opt is under id-control)

end

if opt2.runtype
    fmf = [];
    return
end

stimtype = opt.stimtype;
featid = opt.id;
crop_edges = opt.crop_edges;
rep = opt.rep;
flipped = opt.flipped;
feat2 = opt.feat2;

pthpar_feat = opt2.pthpar;
pth_template = opt2.pthtemplate;
getgrid = opt2.getgrid;%get the feature on a grid (phi theta if vistype is sphere, xy if gridtype is plane)
vistype = opt2.vistype;%sphere, plane, or raw 
it = opt2.it;
gridres = opt2.gridres;
downsample_template = opt2.downsample_template; %downsamples template, then uses it, rather than using template then downsampling; fine for most cases, just looks a little rougher
doplt = opt2.doplt;
optid = opt2.optid;
varid = opt2.varid;

callstack = dbstack();
if ( ~isequal(optid, glbfile('optiddf')) || ~isequal(varid, glbfile('variddf')) ) && ( numel(callstack)<2 || ~isequal(callstack(2).file, [mfilename 'w.m']) )
    error("optid and varid can only be nonempty when calling " + mfilename + " from its wrapper function, " + [mfilename 'w.m'])
end

if isstruct(s)
    pthstack = s.pth;
else
    pthstack = s;
    mustBeTextScalar(pthstack)
end

if ~isfile(pthstack)
    error("input s is either not a valid pthstack, or if s is struct, it does not contain field pth")
end

if strcmp(vistype, 'raw') && getgrid
    error("to get grid, vistype cannot be raw; this is not a grid for flymax features (it is hex values)")
end

if isempty(doplt)
    doplt = any(strcmp('featid', glb('plt')));
end


id = idmake(pthstack);
recdate = id.recdate;
fly = id.fly;
trial = id.trial;
fldr = [num2str(recdate) num2str(fly) ',*'];

spl = strsplit(featid, '_');
stimfeat_type = spl{1};
stimfeat_num = spl{2};


fnpat = [stimtype '_' num2str(trial) '_' num2str(rep) '_' featid '_*_*_.mat'];
pthpat = [pthpar_feat filesep fldr filesep fnpat];

pthall = rdir(pthpat);
pthall = natsortfiles(pthall);

suffix_grid = ['grid_' vistype '_'];

for fi = 1:length(pthall)

    if ~contains(pthall(fi).name, suffix_grid) %first load the feature; load or make the gridded feature next
        pth_stimfeat = pthall(fi).name;
        [pthtmp, fntmp, exttmp] = fileparts(pth_stimfeat);
        stim = struct2cell(load(pth_stimfeat, 'stimulus'));
        stim = stim{1};
        if ~isa(stim, 'single')
            stim = single(stim);
        end
    end


    if doplt || getgrid

        pth_stimgrid = insertBefore(pth_stimfeat, '.mat', suffix_grid);
        if isfile(pth_stimgrid)
            stimgrid = struct2cell(load(pth_stimgrid, 'stimgrid'));
            stimgrid = stimgrid{1};
        else
            fprintf("stimgrid file '" + pth_stimgrid + "' does not exist; making stimgrid now" + newline)
            stimgrid = hex2grid(stim,...
                vistype = vistype,...
                it = it,...
                gridres = gridres,...
                flipped = flipped,...
                downsample_template = downsample_template, ...
                crop_edges = crop_edges,...
                pth_template = pth_template, ...
                cmap = 'rb', ...
                doplt = doplt);
            save(pth_stimgrid, 'stimgrid', '-v7.3', '-mat')
        end

    end


    if ~isempty(feat2)
        fntmp = strrep(fntmp, featid, feat2);
        pth_stim2 = [pthtmp filesep fntmp exttmp];
        load(pth_stim2, 'stim')
        stim2 = struct2cell(load(pth_stim2, 'stimulus'));
        stim2 = stim2{1};
        if ~isa(stim2, 'single')
            stim2 = single(stim2);
        end
    end



end

fmf.stim = stim;
fmf.stimgrid = stimgrid;



