
    %% linear fit and hsv map (will be moved into mdlmake)

    if o.mn.do_lfit


        o.lc.chanuse = 1;

        rindy = 1;
        rsp = ts.roi.(rgname).(parstr.roi.(rgname)).(['imf_f_f_n']);
        stim = ts.vis.CON_51(100,:);

        rsp = ts.roi.(rgname).(parstr.roi.(rgname)).(['imf_f_f_n_chn' num2str(o.lc.chanuse)]);

        [rsp, pwr] = wavflt(rsp, t=ts.t, it=200:900, ir=[1 3], pthgifpre='', wavp=o.roi.wavp, doplt=1, onlyir=1); %pth_roim_prefix

        rsp1 = rsp(rindy,:);

        fvd = ts.ball.forvel;
        fvd = abs(fvd);
        fvd = smoothdata(fvd, 'gaussian', 12, 'omitnan');
        % fvdflt = wavflt(fvd, t=ts.t, wavp=[2 20]); %pth_roim_prefix
        % fvdflt = vecdv('normal', fvdflt, 3, 2, md.sper);
        % tsplt(fvdflt, y2=fvd, xseg=1);

        yvd = ts.ball.yawvel;
        % yvd = abs(yvd);
        yvd = smoothdata(yvd, 'gaussian', 12, 'omitnan');
        %%yvd = vecdv('normal', yvd, 0.4, 2, md.sper);

        tinds = 3000:4000;
        xtrem = max(abs([vec(fvd(tinds)); vec(ts.ball.forvel(tinds))]));
        xtrem = max(abs([vec(fvd(tinds))]));
        figure; plot(rescale(ts.ball.forvel(tinds), -xtrem/1, xtrem/1), Color=[0 0 1 0.1]); yyaxis right; plot(fvd(tinds)); ylim([-xtrem xtrem]); hold on; plot(rescale(rsp1(tinds), -xtrem/8, xtrem/8), 'm-')

        stim = [fvd; yvd];

        % roivpix( ...
        %     ts.roi.(rgname).(parstr.roi.(rgname)).in_imf_pc_f_cl_f_w_no_chn1, ...
        %     stacksub, ...
        %     roidat.(rgname).(parstr.roi.(rgname))(o.lc.chanuse).roipx, ...
        %     t=ts.t, ...
        %     ir=[1:50:1024], ...
        %     it=[1000:1500], ...
        %     yconst=0 ...
        %     );

        lfit( ...
            stim, ..., ts.ball.forvel, ...
            rsp, ... ts.roi.(rgname).(parstr.roi.(rgname)).in_imf_pc_f_cl_f_w_no_chn1, ...
            t = ts.t, ...
            it = 1000:2000, ...
            ir = [], ...
            ipltts = [], ...
            corrtype = 'pearson', ...
            lagsec = linspace(0.15, 0.15, 1e4), ...linspace(0.15, 0.15, 1e4), ...
            lagstyle = 'besteach', ...
            minpval = 0.05, ...
            stack = stacksub, ...
            roipx = roidat.(rgname).(parstr.roi.(rgname))(o.lc.chanuse).roipx, ...
            roiwt = roidat.(rgname).(parstr.roi.(rgname))(o.lc.chanuse).roiwt, ...
            roicen = roidat.(rgname).(parstr.roi.(rgname))(o.lc.chanuse).roicen, ...
            sortstyle = 'slope', ...
            alignzero = 1, ...
            yconst = 0, ...
            plotlagged = 0, ...
            usesaved = 1, ...
            chanuse = o.lc.chanuse, ...
            imhsv = [], ...
            pos = ts.pos, ...
            pixfit = 1, ...
            pthgif = [], ...
            doplt = 1 ...
            );

    end