[ ft(ri,[1:2:12]), pred1(:,ri), resid(:,ri), gof(ri), gof_val1(ri) ] = ...
    mdl_fit(indv(:, [1:2:12]), depv, ri, histinc, ...
    valnum, indv_val, depv_val, sampinds_indvdepv_train, ...
    sampinds_indvdepv_val, num_samp_total, supp, op, ...
    depvmin(ri), depvmax(ri), pthvalsv, nrmd, 1);


[ ft(ri,[2:2:12]), pred2(:,ri), resid2(:,ri), gof(ri), gof_val2(ri) ] = ...
    mdl_fit(indv(:, [2:2:12]), resid(:,ri), ri, histinc, ...
    valnum, indv_val, depv_val, sampinds_indvdepv_train, ...
    sampinds_indvdepv_val, num_samp_total, supp, op, ...
    depvmin(ri), depvmax(ri), pthvalsv, nrmd, 1);


prednew = pred1(:,ri) + pred2(:,ri);
resid = depv - prednew;
gof_val3 = mean((resid).^2);

mdlplt(op.mdl, supp, depv, prednew, ft, indv, nrmd, gof_val3)