function roi = roimake_w(s, opt, opt2)

%{

vg structs are used by vget to find inputs to modules that are main inputs to modules
    for example, s is a variable containing the stack (neural image data), and it is the main input to roimake
    but if name-value argument 's' is a nonempty struct vg, and s is empty, code will find s meeting criteria set in vg, and use that as the main input to roimake
    this is a system for tracking inputs/outputs and how they change with analysis 

%}

arguments
    
    s struct = []; %struct output from function stackld (contains stack, md, pth, and other fields)

    opt.s struct = struct(glbfile('fnvget'), [])
    opt.rgname {mustBeText, mustBeNonempty} = 'none'; %default rgname 'none' automatically gets full fov rg; user is not prompted to create an rg in this case
    opt.roiname {mustBeText, mustBeNonempty} = 'none'; %text, name of roi set created by roimake on a single rg
    opt.dodraw (1,1) {mustBeBinary} = 0 %1 to draw rois in roidraw
    opt.ma struct = [] %roimauto options returned by roimauto('', och=1); empty to skip roimauto; roimauto applies automated morphological roi segmentation
    opt.cm struct = [] %roifauto options returned by roifauto('', och=1); empty to skip roifauto; roifauto calls python caiman roi extraction from matlab (functional and morphological roi segmentation)
    opt.qc struct = [] %roiqc options returned by roiqc('', och=1); empty to skip roiqc; roiqc applies quality control to rois (filtering by size, number, etc)
    opt.nrm struct = [] %roinorm options returned by roinorm('', och=1); empty to skip roinorm; roinorm applies normalization to roi timeseries 
    opt.optid {mustBeTextScalar} = ''; %automatically generated id for each unique input opt set; if your input opt is not generated by oset, leave optid empty
    
    opt2.t (1,:) double = [] %timestamp vector; only required nonempty if channorm~=0 in opt.nrm
    opt2.roimask = [] %roimask to apply to stack; if nonempty, roidraw and roimauto are skipped
    opt2.doplt (1,1) {mustBeBinary} = 0 % 1 to do plots
    opt2.och (1,1) {mustBeBinary} = 0 %och means "options check"; 1 to exit function and return nothing but arguments block struct opt (not opt2 or any other name-value arguments struct); 0 to skip och (run function normally), which is default

end

optout = oid(optout); %assign ids to options sets

if opt2.och
    if isfield(opt, 'optid')
        opt = rmfield(opt, 'optid');
    end
    roi = opt;
    return
end

opt = optidcheck('roi', opt); %make sure optid matches input, if nonempty (if empty, assign it default value)


%% set up s (main variable roimake operates on)

if ~isequal(isempty(s), ~isempty(opt.s.vg))
    error("s or opt.s.vg must be nonempty, but not both")
end

if isempty(s)
    dovget = 1;
else
    dovget = 0;
end

clear vget %clear persistent variables within vget (just in case)
its = 0;
while true
    its = its+1;

    if dovget %if s defined in the options struct, instead of passed in as arguments
        [vdat, s] = vget(its, opt.s);
        pthroi = [vdat.pthc vdat.varid opt.optid '_roi_.mat'];
        varid = vdat.varid;
        last = vdat.last;
    else
        varid = 'z0';
        pthroi = [fileparts(s.pth) filesep varid opt.optid '_roi_.mat'];
        last = 1;
    end

    roi = roimake2(s, opt, opt2, varid, pthroi); %now that we have final version of input variable 's', enter the main roimake function

    if last
        break
    end
end

end

