function [roi, opt, mm] = roimake(s, opt, opt2)

% see docs_roimake.m

arguments
    
    s struct = []; %struct output from function smake (contains stack, md, pth, and other fields)

    opt.rgname {mustBeText, mustBeNonempty} = glbfile('rgnamedf'); %default rgname 'none' automatically gets full fov rg; user is not prompted to create an rg in this case
    opt.roiname {mustBeText, mustBeNonempty} = glbfile('roinamedf'); %text, name of roi set created by roimake on a single rg
    opt.dodraw (1,1) {mustBeBinary} = 0 %1 to draw rois in roidraw
    opt.ma struct = [] %roimauto options returned by roimauto('', runtype=1); empty to skip roimauto; roimauto applies automated morphological roi segmentation
    opt.cm struct = [] %roifauto options returned by roifauto('', runtype=1); empty to skip roifauto; roifauto calls python caiman roi extraction from matlab (functional and morphological roi segmentation)
    opt.qc struct = [] %roiqc options returned by roiqc('', runtype=1); empty to skip roiqc; roiqc applies quality control to rois (filtering by size, number, etc)
    opt.nrm struct = [] %roinorm options returned by roinorm('', runtype=1); empty to skip roinorm; roinorm applies normalization to roi timeseries 
    
    opt2.roimask {mustBeBinary(opt2.roimask,'emptyok')} = [] %roimask to apply to stack; if nonempty, roidraw and roimauto are skipped
    opt2.doplt (1,1) {mustBeBinary} = 0 % 1 to do plots
    opt2.optid {mustBeTextScalar} = glbfile('optiddf') %automatically generated id for unique set of input options; if your input opt is not generated by oset, leave optid empty
    opt2.varid {mustBeTextScalar} = glbfile('variddf') %automatically generated id for unique set of input variables; if your input variables are not generated by vget, leave varid empty
    opt2.runtype (1,1) {mustBeBinary} = 0 %runtype controls how much of this function to run; 0 to run entire function; 1 to do nothing but validate input arguments and return arguments block struct opt (not any other input arguments, since only opt is under id-control)

end

roi = [];
mm = [];

if opt2.runtype
    return
end

rgname = opt.rgname;
roiname = opt.roiname;
dodraw = opt.dodraw;
opt_ma = opt.ma;
opt_cm = opt.cm;
opt_qc = opt.qc;
opt_nrm = opt.nrm;

roimask = opt2.roimask;
doplt = opt2.doplt;
optid = opt2.optid;
varid = opt2.varid;

callstack = dbstack();
if ( ~isequal(optid, glbfile('optiddf')) || ~isequal(varid, glbfile('variddf')) ) && ( numel(callstack)<2 || ~isequal(callstack(2).file, [mfilename 'w.m']) )
    error("optid and varid can only be nonempty when calling " + mfilename + " from its wrapper function, " + [mfilename 'w.m'])
end

if ndims(s.stack)<4 || ndims(s.stack)>5
    error("stack input to roimake must have 4 or 5 dimensions (yxztc)")
end

numchan = size(s.stack,5);

tscm = [];
if isempty(roimask)
    maskin = 0;
    roimask = cell(numchan,1); %needs to be cell in case 2-channel with different number rois
else
    maskin = 1;
    if ~iscell(roimask)
        roimask = {roimask};  %needs to be cell in case 2-channel with different number rois
    end
    if ~isequal(numel(roimask), numchan)
        error("number of channels in input 's.stack' and name-value argument 'roimask' do not match")
    end
end


if ~isempty(s.roi)
    roi = s.roi(cellfun(@(x) isequal(x,optid), {s.roi.optid}) & cellfun(@(x) isequal(x,varid), {s.roi.varid})); %see if requested roi exists in s.roi; if not, make it
end


if isempty(roi)

    fprintf("requested s.roi does not exist" + newline + "creating roi struct now" + newline)


    %%%% OPTIONALLY CROP STACK TO rg CUBOID %%%%

    s = rgmake(s, rgname);


    %%%% DRAW ROIS %%%%

    if dodraw && ~maskin
        mm = roidraw(s, roiname=roiname); %cellout=1 because in roimake roimask is cell (one for each channel)
        roimask = mm.mask;
    end


    %%%% AUTOMATED MORPHOLOGICAL SEGMENTATION %%%%

    if ~isempty(opt_ma) && ~maskin
        prs = struct2pairs(opt_ma);
        roimask = roimauto(s.mnt, prs{:}, roimaskin=roimask, widyxz=s.md.widyxz, roiname=roiname);
    end


    %%%% AUTOMATED FUNCTIONAL SEGMENTATION (CAIMAN) %%%%

    if ~isempty(opt_cm) && ~maskin
        prs = struct2pairs(opt_cm);
        [tscm, roimask] = roifauto(s.stack, prs{:}, rgname=rgname, roiname=roiname);
    end


    %%%% QUALITY CONTROL %%%%

    if ~isempty(opt_qc) && ~maskin
        prs = struct2pairs(opt_qc);
        roimask = roiqc(roimask, prs{:}, trm=trm, roicen=roidat.roicen, mask_allroi=roidat.mask_allroi);
    end


    %%%% COMPUTE ROI TIMESERIES AND NORMALIZE %%%%

    if isempty(tscm)
        [ts, roimask] = roits(s.stack, roimask);
    else
        [ts, roimask] = roits(tscm, roimask);
    end


    %%%% NORMALIZE ROI TIMESERIES %%%%

    if ~isempty(opt_nrm)
        prs = struct2pairs(opt_nrm);
        ts = roinorm(ts, prs{:}, srate=s.md.volrate, t=s.t);
    end


    %%%% ASSEMBLE ROI DATA INTO STRUCT %%%%

    roitmp = roidatmake(s.mnt, roimask);
    roitmp.ts = ts;
    roitmp.opt = opt;
    roitmp.optid = optid;
    roitmp.varid = varid;
    roitmp.maketime_optfile_roi = glb('maketime_roi');
    
    roi = roitmp;

end



%%%% PLOTS %%%%

if doplt && ~maskin

    pthpre = erase(pthroi, '.mat');

    stackplt(s.mnt, roipx=roi.dat(1).roipx)
    
    chanplt = 1;

    imhsv = plots_setup_hsv(opt.imhsv);
    hueft = [1:num_roim]';
    hsvmap = hsvcmp(imhsv, hueft=hueft);
    pthhsv = [pthpre 'hsvfov_.gif'];
    hsvplt(imhsv, s.mnt(:,:,:,:,chanplt), hsvmap, roipx, roiwt, dohsv, pthhsv);

    ptholay = [pthpre 'roioverlay_.gif'];
    gifvis = 'on';
    chanplt = 1;
    stackplt(s.mnt(:,:,:,:,chanplt), pthgif=ptholay, gifvis=gifvis, roipx=roipx, ir=roiol.ir, roicols=roiol.roicol, roialpha=roiol.roialpha) %include roipx as argument to plot roi overlay

    %colormap for each roi
    cmap = distinguishable_colors(size(roiwt,1));
    double_colormap = 0;
    if double_colormap %like for two halves of PB, etc, made this default 0 since the split is just halfway along mask (not functional)
        num_region_periods = 2; %for example, two halves of pb
    else
        num_region_periods = 1;
    end
    cmap = repmat(cmap,num_region_periods,1); %if region is periodic with multiple periods


    %3d scatter, each roi a different hue
    hfg = figure; hold on
    for k = 1:num_roim %overlay each pixel in its indexed color onto the pb image
        scatter3( maskx(idx_vox2roi == k), masky(idx_vox2roi == k), maskz(idx_vox2roi == k), 'filled', 'MarkerFaceColor', cmap(k,:), 'MarkerFaceAlpha', 0.2 )
    end
    %plot3(midx,midy,midz,'.k', 'MarkerSize',12) %include midline if using 'skeleton'
    %scatter3(roicen(:,2 ), roicen(:,1), roicen(:,3), 80, 'k', 'filled') %show the centroids in each of their colors
    colormap(bone);
    axis image; axis off
    set(gca,'Visible','off')
    set(gca,'CameraViewAngle',8)
    rotinc = 30;
    views = -180:rotinc:180;
    pthgif = [pthpre 'huerois_3dspin_.gif'];
    for framecount = 1:length(views) - 1
        view(views(framecount)+2, 20)
        fig2gif(hfg, framecount, pthgif)
    end



    %mask overlay
    overlayarray = rescale(0.2*rescale(mask_allroi) + rescale(s.mnt, 0, 1));
    stackplt( overlayarray, pthgif=[pthpre 'maskallroi_overlay_.gif'])

    %manual roi mask
    stackplt(roimaskman, pthgif=[pthpre 'roimaskman_.gif'])

    %mask all rois (without stack background)
    stackplt(mask_allroi, pthgif=[pthpre 'maskallroi_.gif'])

    % %3d surface plot
    % kbnd = boundary([maskx,masky,maskz]);
    % figure;
    % trisurf(kbnd,maskx',masky',maskz','Facecolor','red','FaceAlpha',0.1)
    % axis image
    % saveas( gcf, [pthpre 'maskallroi_surface_.png'])


end

% if isempty(opt_ma) && strcmp(roisrt, morph_long_axis)
%     fprintf("WARNING, cannot implement roisrt 'morph_long_axis' because ma is empty" + newline)
% end


end

