function roi = roimake(s, opt, opt2)

% see docs_roimake.m

arguments
    
    s struct = []; %struct output from function stackld (contains stack, md, pthstack, and other fields)

    opt.s struct = struct('vg', [])
    opt.rgname {mustBeTextScalar, mustBeNonempty} = 'none'; %default rgname 'none' automatically gets full fov rg; user is not prompted to create an rg in this case
    opt.roiname {mustBeTextScalar, mustBeNonempty} = 'none'; %text, name of roi set created by roimake on a single rg
    opt.dodraw {mustBeMember(opt.dodraw,[0,1]), mustBeNonempty} = 0 %1 to draw rois in roidraw
    opt.ma struct = [] %roimauto options returned by roimauto('', och=1); empty to skip roimauto; roimauto applies automated morphological roi segmentation
    opt.cm struct = [] %roifauto options returned by roifauto('', och=1); empty to skip roifauto; roifauto calls python caiman roi extraction from matlab (functional and morphological roi segmentation)
    opt.qc struct = [] %roiqc options returned by roiqc('', och=1); empty to skip roiqc; roiqc applies quality control to rois (filtering by size, number, etc)
    opt.nrm struct = [] %roinorm options returned by roinorm('', och=1); empty to skip roinorm; roinorm applies normalization to roi timeseries 
    opt.optid {mustBeTextScalar} = ''; %automatically generated id for each unique input opt set; if your input opt is not generated by oset, leave optid empty
    
    opt2.t (1,:) double = [] %timestamp vector; only required nonempty if channorm~=0 in opt.nrm
    opt2.roimask = [] %roimask to apply to stack; if nonempty, roidraw and roimauto are skipped
    opt2.doplt {mustBeMember(opt2.doplt,[0,1]), mustBeNonempty} = 0 %1 to do plots
    opt2.och {mustBeMember(opt2.och,[0,1]), mustBeNonempty} = 0 %och means "options check"; 1 to exit function and return nothing but arguments block struct opt (not opt2 or any other name-value arguments struct); 0 to skip och (run function normally), which is default

end

if opt2.och
    if isfield(opt, 'optid')
        opt = rmfield(opt, 'optid');
    end
    roi = opt;
    return
end

opt = optidcheck('roi', opt); %make sure optid matches input, if nonempty (if empty, assign it default value)


%% set up s (main variable roimake operates on)

if ~isequal(isempty(s), ~isempty(opt.s.vg))
    error("s or opt.s.vg must be nonempty, but not both")
end

if isempty(s)
    dovget = 1;
else
    dovget = 0;
end

clear vget %clear persistent variables within vget (just in case)
its = 0;
while true
    its = its+1;

    if dovget %if s defined in the options struct, instead of passed in as arguments
        [vdat, s] = vget(its, opt.s);
        pthroi = [vdat.pthc vdat.varid opt.optid '_roi_.mat'];
        varid = vdat.varid;
        last = vdat.last;
    else
        varid = 'z0';
        pthroi = [fileparts(s.pth) filesep varid opt.optid '_roi_.mat'];
        last = 1;
    end

    roi = roimake2(s, opt, opt2, varid, pthroi); %now that we have final version of input variable 's', enter the main roimake function

    if last
        break
    end
end

end


%% roimake2 (main function)


function roi = roimake2(s, opt, opt2, varid, pthroi)

rgname = opt.rgname;
roiname = opt.roiname;
dodraw = opt.dodraw;
opt_ma = opt.ma;
opt_cm = opt.cm;
opt_qc = opt.qc;
opt_nrm = opt.nrm;
optid = opt.optid;

t = opt2.t;
roimask = opt2.roimask;
doplt = opt2.doplt;

if ~isfield(s, 'rg') || ~isempty(s.rg)
    error("roimake input s must have field named 'rg', and s.rg must be empty (s.stack cannot be an rg, since roimake>stackcrop creates rg); if rg is not a field in s, or if it is not empty, you might be using an old s, or using an s that has already been passed through stackcrop; if the former, delete stack mat file (not tif) and run the most recent version of stackld to create stack mat file with the new field rg; if the latter, just run stackld again to reload the uncropped stack")
end
pthstack = s.pth;
stack = s.stack;
srate = s.md.volrate;
widyxz = s.md.widyxz;
if isempty(t)
    t = linspace(0,s.md.numvol/s.md.volrate-1/s.md.volrate,s.md.numvol);
end
% s = [];

if ndims(stack)==3
    stack = reshape(stack, size(stack,1), size(stack,2), 1, size(stack,3)); %put t in 4th dim if stack is 3d (assumed to be yxt)
end
if ndims(stack)<4 || ndims(stack)>5
    error("stack input to roidraw must have 4-5 dimensions (yxztc)")
end

numchan = size(stack,5);

mm = [];
tscm = [];
if isempty(roimask)
    maskin = 0;
    roimask = cell(numchan,1); %needs to be cell in case 2-channel with different number rois
else
    maskin = 1;
    if ~iscell(roimask)
        roimask = {roimask};  %needs to be cell in case 2-channel with different number rois
    end
    if ~isequal(numel(roimask), numchan)
        error("number of channels in input 's.stack' and name-value argument 'roimask' do not match")
    end
end



try

    roi = load(pthroi);

    if any(~isfield(roi, {'dat', 'maketime_optfile_roi'})) || isfield(roi, 'ts')
        error("roi struct, at highest level, must contain field and 'dat' (and not field ts); you may have loaded an old roi struct")
    end
    if ~isequal(roi.maketime_optfile_roi, glb('maketime_roi'))
        error("roi id is derived from an optid file different from original")
    end
    [~, rg] = stackcrop(s, rgname); %don't input or output stack here, just loading rg
    [~, mm] = roidraw(s, nodraw=1, roiname=roiname); %don't input stack here, just loading mm
    if ~isequal(roi.dat(1).rg, rg) || ~isequal(roi.dat(1).mm, mm(1)) || ( numel(roi.dat)==2 && ( ~isequal(roi.dat(2).rg, rg) || ~isequal(roi.dat(2).mm, mm(2)) ) )
        error("roi.dat.rg must match rg and roi.dat.mm must match mm; you may have changed rg or mm since saving roi file")
    end
    if ~isfield(roi, 'opt') %doing this check separately from above because added opt to saved variables later than others
        roi.opt = opt;
        save(pthroi, '-struct', 'roi', '-v7.3', '-mat')
    else
        if ~isequal(roi.opt, opt)
            error("opt saved/loaded from roi file does not match input opt")
        end
    end


catch ME


    fprintf("" + ME.message + newline + "creating roi struct now" + newline)


    %%%% OPTIONALLY CROP STACK TO rg CUBOID %%%%

    [s, rg] = stackcrop(s, rgname);

    stackmnt = single(mean(stack, 4)); %compute mean t stack after optional stackcrop (can't remember why we switch to single precision here)


    %%%% DRAW ROIS %%%%

    if dodraw && ~maskin
        prs = struct2pairs(opt_mm);
        [roimask, mm] = roidraw(s, prs{:}, cellout=1); %cellout=1 because in roimake roimask is cell (one for each channel)
    end


    %%%% AUTOMATED MORPHOLOGICAL SEGMENTATION %%%%

    if ~isempty(opt_ma) && ~maskin
        prs = struct2pairs(opt_ma);
        roimask = roimauto(stackmnt, prs{:}, roimaskin=roimask, widyxz=widyxz, pthstack=pthstack, rg=rg, roiname=roiname);
    end


    %%%% AUTOMATED FUNCTIONAL SEGMENTATION (CAIMAN) %%%%

    if ~isempty(opt_cm) && ~maskin
        prs = struct2pairs(opt_cm);
        [tscm, roimask] = roifauto(stack, prs{:}, rgname=rgname, roiname=roiname);
    end


    %%%% QUALITY CONTROL %%%%

    if ~isempty(opt_qc) && ~maskin
        prs = struct2pairs(opt_qc);
        roimask = roiqc(roimask, prs{:}, trm=trm, roicen=roidat.roicen, mask_allroi=roidat.mask_allroi);
    end


    %%%% COMPUTE ROI TIMESERIES AND NORMALIZE %%%%

    if isempty(tscm)
        [ts, roimask] = roits(stack, roimask);
    else
        [ts, roimask] = roits(tscm, roimask);
    end


    %%%% NORMALIZE ROI TIMESERIES %%%%

    if ~isempty(opt_nrm)
        prs = struct2pairs(opt_nrm);
        ts = roinorm(ts, prs{:}, srate=srate, t=t);
    end


    %%%% ASSEMBLE ROI DATA INTO STRUCT %%%%

    roi.dat = roidatmake(stackmnt, roimask, ts, rg, mm, pthstack);


    %%%% SAVE %%%%

    roi.opt = opt;
    roi.varid = varid;
    roi.maketime_optfile_roi = glb('maketime_roi');
    save(pthroi, '-struct', 'roi', '-v7.3', '-mat')


end



%%%% PLOTS %%%%

if doplt && ~maskin

    pthpre = erase(pthroi, '.mat');

    stackplt(roi.dat(1).stackmnt, roipx=roi.dat(1).roipx)
    
    chanplt = 1;

    imhsv = plots_setup_hsv(opt.imhsv);
    hueft = [1:num_roim]';
    hsvmap = hsvcmp(imhsv, hueft=hueft);
    pthhsv = [pthpre 'hsvfov_.gif'];
    hsvplt(imhsv, stackmnt(:,:,:,:,chanplt), hsvmap, roipx, roiwt, dohsv, pthhsv);

    ptholay = [pthpre 'roioverlay_.gif'];
    gifvis = 'on';
    chanplt = 1;
    stackplt(stackmnt(:,:,:,:,chanplt), pthgif=ptholay, gifvis=gifvis, roipx=roipx, ir=roiol.ir, roicols=roiol.roicol, roialpha=roiol.roialpha) %include roipx as argument to plot roi overlay

    %colormap for each roi
    cmap = distinguishable_colors(size(roiwt,1));
    double_colormap = 0;
    if double_colormap %like for two halves of PB, etc, made this default 0 since the split is just halfway along mask (not functional)
        num_region_periods = 2; %for example, two halves of pb
    else
        num_region_periods = 1;
    end
    cmap = repmat(cmap,num_region_periods,1); %if region is periodic with multiple periods


    %3d scatter, each roi a different hue
    hfg = figure; hold on
    for k = 1:num_roim %overlay each pixel in its indexed color onto the pb image
        scatter3( maskx(idx_vox2roi == k), masky(idx_vox2roi == k), maskz(idx_vox2roi == k), 'filled', 'MarkerFaceColor', cmap(k,:), 'MarkerFaceAlpha', 0.2 )
    end
    %plot3(midx,midy,midz,'.k', 'MarkerSize',12) %include midline if using 'skeleton'
    %scatter3(roicen(:,2 ), roicen(:,1), roicen(:,3), 80, 'k', 'filled') %show the centroids in each of their colors
    colormap(bone);
    axis image; axis off
    set(gca,'Visible','off')
    set(gca,'CameraViewAngle',8)
    rotinc = 30;
    views = -180:rotinc:180;
    pthgif = [pthpre 'huerois_3dspin_.gif'];
    for framecount = 1:length(views) - 1
        view(views(framecount)+2, 20)
        fig2gif(hfg, framecount, pthgif)
    end



    %mask overlay
    overlayarray = rescale(0.2*rescale(mask_allroi) + rescale(stackmnt, 0, 1));
    stackplt( overlayarray, pthgif=[pthpre 'maskallroi_overlay_.gif'])

    %manual roi mask
    stackplt(roimaskman, pthgif=[pthpre 'roimaskman_.gif'])

    %mask all rois (without stack background)
    stackplt(mask_allroi, pthgif=[pthpre 'maskallroi_.gif'])

    % %3d surface plot
    % kbnd = boundary([maskx,masky,maskz]);
    % figure;
    % trisurf(kbnd,maskx',masky',maskz','Facecolor','red','FaceAlpha',0.1)
    % axis image
    % saveas( gcf, [pthpre 'maskallroi_surface_.png'])


end

% if isempty(opt_ma) && strcmp(roisrt, morph_long_axis)
%     fprintf("WARNING, cannot implement roisrt 'morph_long_axis' because ma is empty" + newline)
% end


end

