function todo()

disp("eventually make rg and mm have check that stack input has not changed, with stack's optid from sld")
disp("make all pthscopa calls glb?")
disp("fix all eval calls, eg in structunflat")
disp("fix order of module inputs, should opt be first, or just first name-value argument?")
disp("remove calls to combos since it relies on a toolbox")
disp("distribution in tsget?? can tg fields be distributed when cells? or is the group field doing that but with less flexibility?")
disp("give mn an ored so that if no do for a module, that vbin is empty in  options struct, or just hard code that")
disp("optid not getting assigned for mdl from within bmp")
disp("save opt with each module's save")
disp("make tsget have option to retrieve the index of all found timeseries, so you don't output all of them and then index that, but instead output only the desired combo index ")
disp("make '__' delim in structflat a global ")
disp("use dbstack to prevent some functions from running unless a2p is on stack (like tsget maybe; in general because of reliance on glb)")
disp("the useprefix problem has to be fixed, although thre only time an optid is searched for by name with structfile is in fset, so that's the only time there's an odd hack (removing prefix before passing to structfile")
disp("should empty optid be part of each struct in defaults? or only added after oid, as it does now?")
disp("change names for tsget group")
disp("tsget defaults are never filled in on purpose, but is that right?")
disp("make daqld ftv have a dotfv, just like roimake")
disp("consider making default nested opts rather than using nestvalid; for example, d.roi.cm = [], etc")
disp("optid for stackseries, since it affects the rois")
disp("no roeason to make daq a table in daqld then convert to struct, just m,ake struct from start")
disp("in tsget there are multiple files with matched optid and domain, you may have created them from different versions of the same stack (cmrg, dcdn, etc); need to make this fixible; for now just rename one")
disp("do i need maketime protection for rg??")
disp("in odfsv define timeseries fields available to bmp (like mu, rho, amp, etc), the way you did with daq, do this for all main modules ")
disp("tsget is limited to one vbin within tg at a time but shouldn't be, what if you want a daq and roi variable as indv")
disp("deal woith how structfile nm does not incolude prefix but in the txt file the structs are named with [prefix nm]; confusing")
disp("make sure optids refer to same file, that the opt file mapping opt to id has not been changed ")
disp("nonfunctional vbin in ored/odist etc need to be able to be nested and returned to right spot")
disp("set up default roimake, where opt can be empty) - mean of fov")
disp("need to make nan for cue in dark now that epoch is loaded on daq")
disp("now if multiple recind are running in pl.sh, and one errors, the whole sequence will stop (i think only at the do copyfiles part though, so maybe if docopyfiles is 0 the recind without error will continue??) is this good or bad?")
disp("should maskname none be reserved for skipping drawing?")
disp("right now opts thsat get written to opt file are only functional, and if entire vbin are non-functional (ignored) they are written as empty struct which is {} in txt file; is this best? should all ignored options get written as empty or nan or something like that? that seems like a lot of clutter")
disp("odf argument unpack should unpack to the specified nest if vbin is nested, currently it just unnpacks the highest level, or if that might cause issue somewhere, make an unpack nest option")
disp("TEMPORARY HACK FOR CROPPING NEW RUNBG DAQ (WHEN DAQ RUNS IN BACKGROUND, TO CAPTURE START AND END OF EVERYTHING) output data is less accurate than frameClock, since volume (or frame?) seems to complete after outputData ends, but i think frameClock is missing any final flyback frames")
disp("should ftv downsampling occur in ftvpr in matlab? why do it in pythno during register?? oh it's because matlab on mac can't read it??")
disp("daq needs toindex, like doballscale etc, to convert binary to index, right now it happens by default in daqpr for any binary variable, but what if you want it to remain binary?? it should also occur outside daqpr, like the other to* variables, but this one before daqpr")
disp("make substr have convenient start finish markers, rather than having to use ^ and $ where the option is specified")
disp("make methodmm sum to draw on sum of channels")
disp("make channel consistently 5th dim index or pmt index; right now in python code it's pmt index and in matlab it's mostly stack 5th dim index")
disp("make sure fictrac has not flatlined, epoch might be as expected despite fictrac flatline")
disp("write function to delete a variable in txt (not allow manual) that will also delete all associated files")
disp("\n\nSTITCH IS INDEPENDENT FOR 2 CHANNELS, FIX THAT? OR IS THAT FINE??")
disp("apply tsdv to daq directly, not output of tsrs")
disp("make vsmooth for all variables rather than stacksm and tssm")
disp("MAKE TIME ALWAYS 2ND DIM")
disp("FIX DIFFERENT roi OPTS FOR EACH RGNAME, OR MAYBE TRANSFER MANY PARAMS TO OPTS IN THEIR FUNCTIONS")
disp("CAN STACK REMAIN INT16?? zero in uint16 is nice though")
disp("MAKE ALL INDICES CONSISTENTLY REPRESENT START, CENTER, OR END . . . daq starts at 0, so maybe do start indexed, but singleton 0 indexed samples don't tell you width; but currently default daq downsampling makes time represent center, since it takeds average")
disp("make hemisphere option (eg option to analyze left or right or both)")
disp("fix hsv spec for internal periodic components (vonmises in fnet gets periodic hue spec)")
disp("need to make mdl_parse_mdlname_string run with other inputs ignored during param setting to check the syntax (so you don't find out later, halfway through the pipeline")
disp("allow recursive mdl")
disp("constrain amplitude of all intermediate functions")
disp("time in all functions")
disp("IS THERE RECORD OF ORIGINAL Z IN ROI??????")
disp("IS THERE RECORD OF ORIGINAL Z IN ROI??????")
disp("IS THERE RECORD OF ORIGINAL Z IN ROI??????")
disp("IS THERE RECORD OF ORIGINAL Z IN ROI??????")
disp("IS THERE RECORD OF ORIGINAL Z IN ROI??????")
disp("IS THERE RECORD OF ORIGINAL Z IN ROI??????")
disp("IS THERE RECORD OF ORIGINAL Z IN ROI??????")
disp("fix hard coded, field-dependent nesting in vnm")
fprintf("FOR NORMAL AND CIRCULAR VARIABLES, CONSIDER A SWITCH FROM MEAN TO INTERP NEAREST WHEN THERE ARE MANY FLYBACK FRAMES, OR WHEN VOLRTE IS LOW, SINCE INCLUDING THOSE IS IN MEAN IS MISLEADING (IF THEY ARE INCLUDED WITH usefbf=1)" + newline)
fprintf("empty in oset invokles defaults becausde it's the same as not existing, do we want that?")
pause(2)

end