function [x, lab] = vecsub(x, opt)

%{

subset vector
output x is subset of name-value argument 'superset'
if input x is vector subset of superset, input x and output x are equal
if input x is one of the valid shorthand operators, and superset is nonempty, output x is derived from superset (depending on shorthand)
    --if input x is empty, output x equals superset
    --if input x is negative integer scalar, x=linspace(superset(1), superset(end), x) 
    --if input x is fractional positive scalar, fractional part is number of equispaced segments in entire superset, and integer part is number of elements in each segment
if name-value argument dosort=1, superset is sorted before applying subset operation
if superset is empty, shorthand operators cannot be used 
if superset is empty, and input x is not a shorthand operator, input x and output x are equal
output x matches orientation of superset
output lab is character vector label for output x

%}


arguments
    x = [] %input x, translated into output x from various shorthand
    opt.superset = [] %if nonempty, superset of which output x must be member (error if not member of superset); if empty, output x is simply same as input x
    opt.dosort = 0 %sort superset before applying special operators
    opt.reg = 'start'; %reg means register of output generated by fractional input x; if reg='start', first element of output x is first element of superset, if reg='end', last element of output x is last element of superset,
    opt.labprefix char = '' %for label, prefix (name) of output vector x
    opt.labdelim char = ',' %for label, delimiter separating each vector element in lab
    opt.labmaxn = 20 %max num char to print
end
superset = opt.superset;
dosort = opt.dosort;
reg = opt.reg;
labprefix = opt.labprefix;
labdelim = opt.labdelim;
labmaxn = opt.labmaxn;


if ~isempty(x) && ~isvector(x)
    error("input x must be empty or vector")
end
if ~isempty(superset) && ~isvector(superset)
    error("name-value argument superset must be empty or vector")
end

emptyop = 0;
if isempty(x)
    if isempty(superset)
        error("to use empty input x as 'all elements' operator, you must pass in name-value argument 'superset' as a reference")
    else
        emptyop = 1;
    end
end

negop = 0;
if all(x<0)
    if isscalar(x)
        if mod(x, 1)==0
            if isempty(superset)
                error("to use negative input x as linspace operator, you must pass in name-value argument 'superset' as a reference")
            else
                negop = 1;
            end
        else
            error("to use negative input x as linspace operator, negative input x must be integer")
        end
    else
        error("to use negative input x as linspace operator, negative input x must be scalar")
    end
end

fracop = 0;
if all(mod(x, 1)~=0)
    if isscalar(x)
        if x>0
            if isempty(superset)
                error("to use fractional input x as discontiguous vector operator, you must pass in name-value argument 'superset' as a reference")
            else
                fracop = 1;
            end
        else
            error("to use fractional input x as discontiguous vector operator, fractional input x must be positive")
        end
    else
        error("to use fractional input x as discontiguous vector operator, fractional input x must be scalar")
    end
end

if dosort
    superset = sort(superset);
end

lab = [];
if emptyop
    x = superset;
elseif negop
    if -x<=numel(superset)
        x = round(linspace(superset(1), superset(end), -x));
    else
        error("negative input x is requesting more elements than exist in superset")
    end
elseif fracop
    numseg = fix(x);
    factmp = 10^(numel(num2str(x))-numel(num2str(numseg))-1);
    seglength = mod(x,1)*factmp;
    seglength = round(seglength);
    segspacing = floor(numel(superset)/numseg);
    seginc = 1;
    if strcmp(reg, 'start')
        ix = [1:seginc:seglength]'+segspacing*([1:numseg]-1);
    elseif strcmp(reg, 'end')
        ix = [1:seginc:seglength]'+segspacing*([1:numseg]-1)+segspacing-seglength;
    else
        error("reg must be 'start' or 'end'")
    end
    if numel(ix)>numel(superset) || any(ix<0, 'all')
        fprintf("seglength*numseg exceeds numel(superset), output will equal superset" + newline)
        x = superset;
    else
        x = superset(ix);
    end
    if numseg*2<=labmaxn && seglength~=1 %special label for fractional input x (not created by 
        lab = cell(1,size(x,2));
        for k = 1:size(x,2)
            lab{k} = [num2str(x(1,k)) ':' num2str(x(end,k))];
        end
        lab = strjoin(lab, ',');
    end
end

x = x(:);
if isrow(superset)
    x = x';
end

if ~isempty(superset) && any(~ismember(x, superset)) && ~all(isnan(x))
    error("at least one element of x is outside superset")
end

if isempty(lab)
    lab = num2lab(x, delim=labdelim, prefix=labprefix, maxn=labmaxn);
end

end

